import type { ConnectionProfile, LocalFsEntry, SftpEntry, SftpTransferProgressPayload } from '../../types';

export type SftpViewProps = {
  isActive: boolean;
  profiles: ConnectionProfile[];
  selectedSftpProfileId: string;
  selectedSftpProfile: ConnectionProfile | null;
  connectedSftpProfile: ConnectionProfile | null;
  sftpBusy: boolean;
  sftpMessage: string | null;
  sftpPath: string;
  sftpPathInput: string;
  sftpEntries: SftpEntry[];
  sftpSelectedPath: string | null;
  localPath: string;
  localPathInput: string;
  localParentPath: string | null;
  localEntries: LocalFsEntry[];
  localBusy: boolean;
  localMessage: string | null;
  localSelectedPath: string | null;
  localTransferProgresses: SftpTransferProgressPayload[];
  localCompletedTransferProgresses: SftpTransferProgressPayload[];
  sftpTransferProgresses: SftpTransferProgressPayload[];
  sftpCompletedTransferProgresses: SftpTransferProgressPayload[];
  formatBytes: (value?: number) => string;
  formatUnixTime: (value?: number) => string;
  onSelectSftpProfile: (profileId: string) => void;
  onConnectSftpHost: () => void;
  onRefreshConnectedSftpHost: () => void;
  onDisconnectSftpHost: () => void;
  onSftpPathInputChange: (value: string) => void;
  onOpenSftpPath: () => void;
  onSftpGoParent: () => void;
  onSftpEnterDir: (entry: SftpEntry) => void;
  onSftpDownload: (entry: SftpEntry) => void;
  onSftpSelectPath: (path: string) => void;
  onOpenSftpContextMenu: (x: number, y: number, entry: SftpEntry | null) => void;
  onLocalPathInputChange: (value: string) => void;
  onLocalOpenPath: () => void;
  onLocalGoParent: () => void;
  onRefreshLocalDir: () => void;
  onLocalEnterDir: (entry: LocalFsEntry) => void;
  onLocalSelectPath: (path: string) => void;
  onOpenLocalContextMenu: (x: number, y: number, entry: LocalFsEntry | null) => void;
  onOpenCreateEditor: () => void;
  onCancelUpload: (transferId: string) => void;
  onCancelDownload: (transferId: string) => void;
  onClearLocalCompletedTransfers: () => void;
  onClearSftpCompletedTransfers: () => void;
  onUploadLocalEntryToRemote: (entry: LocalFsEntry) => void;
  onDownloadRemoteEntryToLocal: (entry: SftpEntry) => void;
  onUploadSystemPathsToRemote: (paths: string[]) => void;
};
